### ISSUE TITLE
Change the domain to search

### ISSUE THREAD

**Issue by haavarstein** [controlup/environment-scripts#21]
Please add a -Server option to specify the domain to search in AD_Sync.ps1. By default it will search the Joined Domain, e.g. US but we also to sync sub domains like EU & AP.

https://techcommunity.microsoft.com/t5/windows-powershell/change-the-domain-to-search-with-powershell/m-p/1107716

Error : Get-OU : No OU's were found with the distinguishedName: OU=Citrix,OU=IT,DC=eu

**Comment by Trentent** [comment]
Added -Domain switch to the AD_Sync script.

Erik, my understanding is this should resolve your issue.  I'm going to close this issue. If this did not resolve your issue please reopen the issue.
