### ISSUE TITLE
Not Able to use single universal account in other regional monitor servers while running CTX_Sync.ps1

### ISSUE THREAD

**Issue by udjajoo** [controlup/environment-scripts#31]
Received this error while executing the CTX_Sync.ps1 script to synchronize the ControlUp folder structure with the EUC environment. It returns error stating below:
+ Build-CUTree took: 0 Seconds.
+ Committing Changes:
	> Executing Folder Object Adds. Batch 1/3
Publish-CUUpdates : Invalid user. The user must belong to the same doamin as the insatlled ControlUp Monitor belongs to
At C:\Scripts\Build-CUTree.ps1:299 char:31
+                     $result = Publish-CUUpdates -Batch $batch

**Comment by LandonWinburn** [comment]
Hi Udjajoo,

This can probably be resolved by adding a service account for the second domain as a new domain identity in your monitor settings. Once the monitor has proper credentials for this second domain it should clear the error your getting.
